---
# handlers file for artifactory

- name: systemctl daemon-reload
  ansible.builtin.systemd:
    daemon_reload: true

- name: Restart artifactory
  ansible.builtin.service:
    name: artifactory
    state: restarted
  when:
    - not artifactory_service_started.changed | bool
